apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-dev
  namespace: production
spec:
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      imagePullSecrets:
      - name: dockerhub-private
      containers:
      - name: landing-page
        image: hiro99/landing-page:0.0.1-prod
        ports:
        - containerPort: 80
