apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: staging
spec:
  type: LoadBalancer
  selector: 
    app: wordpress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80