apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-pesbuk
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: fesbuk.cupu69.xyz
    http: 
      paths:
      - backend:
          serviceName: svc-pesbuk
          servicePort: 80